version: '3'

services:
    hyperf:
        build: .
        image: wuchuheng/hyperf:0.0.1
        ports:
            - "9501:9501"
        volumes:
            - ./:/opt/www/
        privileged: true
        container_name: hyperf_container
